### ISSUE TITLE
Error in mapDataUsingRowHeightIndex.js when cell contains too many newline symbols

### ISSUE THREAD

**Issue by yarikos** [gajus/table#22]
This code

``` js
const table = require('table');

const config = {
    columnDefault: {
        width: 5
    },
    columnCount: 3
};
const stream = table.createStream(config);

const lastCell = '\na\n2\n3';

stream.write([1, 2, 3]);
stream.write([1, 2, lastCell]);
```

fails with following error:

``` sh
╔═══════╤═══════╤═══════╗
║ 1     │ 2     │ 3     ║
╚═══════╧═══════╧═══════╝/path_to_prj/node_modules/table/dist/mapDataUsingRowHeightIndex.js:49
        rowHeight[index2][index1] = part;
                                  ^

TypeError: Cannot set property '2' of undefined
at _lodash2.default.forEach (/path_to_prj/node_modules/table/dist/mapDataUsingRowHeightIndex.js:49:35)
...
```

Node v6.5.0.

**Comment by gajus** [comment]
Have you tried debugging this at all?

**Comment by joepie91** [comment]
Experiencing the same issue here, using version 3.8.3.

Reproducable testcase:

```javascript
'use strict';

const table = require("table");

table.default([ [ 0, 'PC', 'SC2KSEPC', '1/1', 24, 'Mon, Apr 13, 1998 8:28 PM' ],
  [ 1, 'PC', 'SC2KSEPC', '1/1', 24, 'Mon, Apr 13, 1998 8:28 PM' ],
  [ 2,
    '\u0000P\u0000C\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000',
    '\u0000S\u0000C\u00002\u0000K\u0000S\u0000E\u0000P\u0000C\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000',
    '1/1',
    25,
    'Mon, Apr 13, 1998 8:28 PM' ],
  [ 3, '', '', 'undefined/undefined', '', '' ] ]);
```

Error:

```
/home/sven/projects/iso-spider/node_modules/table/dist/mapDataUsingRowHeightIndex.js:49
        rowHeight[index2][index1] = part;
                                  ^

TypeError: Cannot set property '1' of undefined
    at _lodash2.default.forEach (/home/sven/projects/iso-spider/node_modules/table/dist/mapDataUsingRowHeightIndex.js:49:35)
    at arrayEach (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:9289:14)
    at _lodash2.default.forEach (/home/sven/projects/iso-spider/node_modules/table/dist/mapDataUsingRowHeightIndex.js:48:24)
    at arrayEach (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:9289:14)
    at _lodash2.default.map (/home/sven/projects/iso-spider/node_modules/table/dist/mapDataUsingRowHeightIndex.js:39:22)
    at arrayMap (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:645:23)
    at Function.map (/home/sven/projects/iso-spider/node_modules/table/node_modules/lodash/lodash.js:9505:14)
    at exports.default (/home/sven/projects/iso-spider/node_modules/table/dist/mapDataUsingRowHeightIndex.js:30:39)
```

Not sure what else there is to debug here, given that I don't know how this module works internally, and the error gives absolutely no useful indication of what might be wrong here.

**Comment by gajus** [comment]
What is the purpose of the `\u0000` in a string?

**Comment by gajus** [comment]
It prints the same thing as far as I can tell:

```js
> console.log('a\u0000b\u0000c\u0000');
VM98:1 abc
> console.log("a\u0000b\u0000c\u0000");
VM104:1 abc
```

Is it safe to strip it out then?

**Comment by joepie91** [comment]
For the sake of people reading along with this thread, from a conversation on IRC:

```
[Sunday, October 23, 2016] [06:10:39 PM] <joepie91>     gajus: it's a UCS-2 thing
[Sunday, October 23, 2016] [06:10:48 PM] <joepie91>     UCS-2 is like fixed-width UTF-16
[Sunday, October 23, 2016] [06:11:00 PM] <joepie91>     so all ASCII chars are prefixed with a nullbyte
[Sunday, October 23, 2016] [06:11:25 PM] <joepie91>     but yes, in canonical text display it doesn't have a graphical representation
```

**Comment by nam-hle** [comment]
I tried to reproduce the error but everything works fine. 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/28835226/115984126-a5003680-a5cf-11eb-8de5-29165128d8fc.png">

**Comment by nam-hle** [comment]
This issue could be closed as well, like [comment](https://github.com/gajus/table/issues/46#issuecomment-829843503)
