### ISSUE TITLE
Streaming - columnSizeIndex.map is not a function

### ISSUE THREAD

**Issue by HACKHERS** [gajus/table#64]
Hello, I have a problem with streaming. I used example code only difference is I changed import with require as `const {createStream} = require("table");`

```
  const columns = columnSizeIndex.map(size => {
                                  ^

TypeError: columnSizeIndex.map is not a function
    at drawBorder (C:\nodejs\node_modules\table\dist\drawBorder.js:20:35)
    at drawBorderTop (C:\nodejs\node_modules\table\dist\drawBorder.js:41:10)
    at create (C:\nodejs\node_modules\table\dist\createStream.js:85:43)
    at Object.write (C:\nodejs\node_modules\table\dist\createStream.js:151:16)
    at Timeout.setInterval [as _onTimeout] (C:\nodejs\index.js:70:12)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
```

**Comment by norfair00** [comment]
I have this error
code from https://github.com/gajus/table/blob/master/.SANDBOX/test-streaming.js
````
/home/n00/sbots/steambot_slave/node_modules/table/dist/drawBorder.js:20
  const columns = columnSizeIndex.map(size => {
                                  ^

TypeError: columnSizeIndex.map is not a function
    at drawBorder (/home/n00/sbots/steambot_slave/node_modules/table/dist/drawBorder.js:20:35)
    at drawBorderTop (/home/n00/sbots/steambot_slave/node_modules/table/dist/drawBorder.js:41:10)
    at create (/home/n00/sbots/steambot_slave/node_modules/table/dist/createStream.js:85:43)
    at Object.write (/home/n00/sbots/steambot_slave/node_modules/table/dist/createStream.js:151:16)
    at Timeout.setInterval [as _onTimeout] (/home/n00/sbots/steambot_slave/slave.js:29:12)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by max-block** [comment]
I have the same error with the code from README.md:

```
const { createStream } = require("table")

let config, stream

config = {
  columnDefault: {
    width: 50
  },
  columnCount: 1
}

stream = createStream(config)

setInterval(() => {
  stream.write([new Date()])
}, 500)
```

Output:
```
maxblock@mbp t3 $ node index.js
/Users/maxblock/projects/tmp/t3/node_modules/table/dist/drawBorder.js:20
  const columns = columnSizeIndex.map(size => {
                                  ^

TypeError: columnSizeIndex.map is not a function
    at drawBorder (/Users/maxblock/projects/tmp/t3/node_modules/table/dist/drawBorder.js:20:35)
    at drawBorderTop (/Users/maxblock/projects/tmp/t3/node_modules/table/dist/drawBorder.js:41:10)
    at create (/Users/maxblock/projects/tmp/t3/node_modules/table/dist/createStream.js:85:43)
    at Object.write (/Users/maxblock/projects/tmp/t3/node_modules/table/dist/createStream.js:151:16)
    at Timeout.setInterval [as _onTimeout] (/Users/maxblock/projects/tmp/t3/index.js:15:10)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

Node: v9.9.0, table: 4.0.3

**Comment by svarkey** [comment]
Reverted to table@3.8.3 and the problem is gone

**Comment by gajus** [comment]
It is open-source package. I don't have resources to inspect this issue at the moment. However, PR would be welcome.

**Comment by steveooo9** [comment]
@gajus This PR seems to work. Could you quickly merge this PR fix and publish a new version?
