### ISSUE TITLE
Terminal Links dont work

### ISSUE THREAD

**Issue by hipstersmoothie** [gajus/table#82]
I am trying to use https://github.com/sindresorhus/terminal-link

First I got the error

```
(node:6881) UnhandledPromiseRejectionWarning: Error: Table data must not contain control characters.
    at validateTableData (/Users/alisowski/Documents/perf-table/node_modules/table/dist/validateTableData.js:62:19)
    at table (/Users/alisowski/Documents/perf-table/node_modules/table/dist/table.js:95:34)
    at Object.<anonymous> (/Users/alisowski/Documents/perf-table/dist/index.js:221:36)
    at step (/Users/alisowski/Documents/perf-table/dist/index.js:43:23)
    at Object.next (/Users/alisowski/Documents/perf-table/dist/index.js:24:53)
    at fulfilled (/Users/alisowski/Documents/perf-table/dist/index.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

After commenting out the code that threw the error It output 

![screen shot 2018-10-02 at 11 37 33 am](https://user-images.githubusercontent.com/1192452/46369439-d55ddf00-c637-11e8-9a63-39bb1906f534.png)

Do you think it will be possible to terminal links inside of the table?

**Comment by gajus** [comment]
This should be straightforward – just whitelist the control characters used to create the terminal links.

Would accept a PR.

**Comment by VeronQ** [comment]
Is this fixed?
Could someone provide an example?
