### ISSUE TITLE
Dont use  prefix with ^

### ISSUE THREAD

**Issue by alerg** [gajus/table#84]
https://github.com/gajus/table/blob/af8688d1d7372090bef8b0c5b051bcac0729b9f0/package.json#L8

the use of the prefix caused ^ your application to download a higher version of the ajv package that eliminated code that your package uses, therefore, I stopped working with webpack buid versions higher than 7.0.0.

`Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`

**Comment by gajus** [comment]
Thats a problem with ajv making a release that is breaking semver rules, not the use of `^`.

**Comment by molinto** [comment]
Same problem here, I have to use v6.9.5 for a physical box. 
My code is running eslint ^5.16.0, which uses your "table": "^5.2.3". 

This no longer builds as latest version of table requires eslint": "^6.0.1" - which in turn needs Node version 8. even though your engine is "node": ">=6.0.0".

I have to remove eslint altogether to fix.
